require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks! :linkage => :static # for react-native-firebase
$RNFirebaseAsStaticFramework = true # for react-native-firebase

# [START] shared config
config = use_native_modules!

# Flags change depending on the env values.
flags = get_default_flags()

use_react_native!(
                  :path => config[:reactNativePath],
                  # Hermes is now enabled by default. Disable by setting this flag to false.
                  # Upcoming versions of React Native may rely on get_default_flags(), but
                  # we make it explicit here to aid in the React Native upgrade process.
                  :hermes_enabled => true,
                  :fabric_enabled => flags[:fabric_enabled],
                  # Enables Flipper.
                  #
                  # Note that if you have use_frameworks! enabled, Flipper will not work and
                  # you should disable the next line.
                  # :flipper_configuration => FlipperConfiguration.enabled, # disable for react-native-firebase
                  # An absolute path to your application root.
                  :app_path => "#{Pod::Config.instance.installation_root}/.."
                  )

post_install do |installer|
  react_native_post_install(
                            installer,
                            # Set `mac_catalyst_enabled` to `true` in order to apply patches
                            # necessary for Mac Catalyst builds
                            :mac_catalyst_enabled => false
                            )
                            __apply_Xcode_12_5_M1_post_install_workaround(installer)
                            
                            # [START] fix build xcode build issue
                            # https://github.com/CocoaPods/CocoaPods/issues/11402
                            installer.pods_project.targets.each do |target|
                              if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
                                target.build_configurations.each do |config|
                                  config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
                                end
                              end
                              # [START] fix sharedApplication build error
                              # https://stackoverflow.com/questions/48122769/facebook-cocoapods-sharedapplication-is-unavailable-not-available-on-ios-app
                              target.build_configurations.each do |config|
                                config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
                              end
                            # [END] fix build xcode build issue 
                            end
                            # [END] fix build xcode build issue
end
# [END] shared config

target 'Production' do
  target 'ShoutoutTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'Development' do
end

target 'ImageNotification' do
  pod 'Firebase/Messaging', '~> 10.4.0' # get version from Podfile.lock
end